package com.example.homeawaytestapp.utils

const val BASE_URL = "https://api.foursquare.com"
const val CLIENT_ID = "UN0PZM1O0Y2AHXMKU4TUQF5AJ3DZG4RBNHKD4LULDSEF5I44"
const val CLIENT_SECRET = "VKD2ZRLKB5KVO5TRAZSE0FCDS3W4PUCR0ZLXKLKLIOMSXIFV"
const val GOOGLE_API_KEY = "AIzaSyBKwY0bSikqr3su0M56fGNkFfYXgYD2als"
const val GOOGLE_MAPS_KEY ="AIzaSyARVBnIIgXYM8tdeoM5w4stMhTIJKHmPIM"
const val DEFAULT_NEAR = "Seattle,+WA"
const val MAIN_LATITUDE = 47.608013
const val MAIN_LONGITUDE = -122.335167
